09_m2m/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movie_pjt/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movie_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list, name='list'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:movie_pk>', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/scores/new', views.movie_score_new, name='movie_score_new'),
    path('<int:movie_pk>/scores/<int:score_id>/delete', views.movie_score_delete, name='movie_score_delete'),
]

movie_pjt/movies/models.py
from django.db import models
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

class Score(models.Model):
    content = models.CharField(max_length=200)
    value = models.IntegerField()
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='score_user',on_delete=True)
    

movies/forms.py
from django import forms
from .models import Genre,Movie,Score

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        
class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['content','value',]

movie_pjt/movies/views.py
from django.shortcuts import render

# Create your views here.
def list(request):
    return render(request, 'movies/list.html')

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Genre,Movie,Score
from .forms import *
from django.views.decorators.http import require_POST

# Create your views here.
def list(request):
    movielist = Movie.objects.all()
    return render(request, 'movies/list.html',{'movielist':movielist})
    
def movie_detail(request,movie_pk):
    movie = get_object_or_404(Movie,id=movie_pk)
    score_form = ScoreForm()
    return render(request, 'movies/movie_detail.html',{'movie':movie,'score_form':score_form})
    
@login_required
@require_POST
def movie_score_new(request,movie_pk):
    score_form = ScoreForm(request.POST)
    if score_form.is_valid():
        score = score_form.save(commit=False)
        score.user = request.user
        score.movie = Movie.objects.get(id=movie_pk)
        score.save()
        return redirect("movies:movie_detail",movie_pk)
    else:
        return redirect("movies:list")

@login_required
def movie_score_delete(request,movie_pk,score_id):
    score = Score.objects.get(id=score_id)
    if score.user == request.user:
        score.delete()
    return redirect("movies:movie_detail", movie_pk)

movies/templates/movies/list.html
{% extends 'base.html' %}
{% block body %}
<h1>Movies List</h1>
{% for movie in movielist %}
<div class="card border-light mb-5">
  <div class="card-header">
      <h1>
          {{movie.title}}
          <div class="btn btn-success">{{movie.audience}} 명</div>
      </h1>
      
  </div>
  <div class="card-body">
    <a href="{% url 'movies:movie_detail' movie.id %}">
          <img src="{{movie.poster_url}}" class="card-img-top" alt="...">
    </a>
    <h5 class="card-title"></h5>
    <p class="card-text">{{movie.description}}</p>
  </div>
</div>
    
    
    
    
    
{% endfor %}
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% block body %}
<div class="card m-5">
  <div class="card-body">
    <h1 class="card-title">
      {{movie.title}}
      <span class="badge badge-success">{{movie.audience}}명</span>
    </h1>
    <div class="row">
      <div class="col col-sm-3 col-xl-2">
        <img class="w-100" src="{{movie.poster_url}}">    
      </div>
      <div class="col col-sm-9 col-xl-10">
        {{movie.description}}
      </div>
    </div>
    <!--댓글을 보여주는 부분-->
    <ul class="list-group list-group-flush">
      {% for comment in movie.score_set.all %}
      <li class="list-group-item">{{comment.user}} :
      {{comment.content}}
      {% if comment.user == user %}
      
      <a href="{% url 'movies:movie_score_delete' movie.id comment.id %}" class="btn btn-danger p-1"><small>삭제</small></a></li>
       {% else %}
       </li>
      {% endif %}
      {% empty%}
      <li class="list-group-item">댓글이 없어요 ㅠㅠㅠ</li>
    {% endfor %}
    </ul>
  </div>
</div>
    
    
  
<form action="{% url 'movies:movie_score_new' movie.id %}" method='post'>
  {% csrf_token %}
  {{score_form}}
  <input type="submit"/>
</form>
    
    
    
    
{% endblock %}