09_m2m/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('',views.user_list,name='user_list'),
    path('<int:user_pk>/', views.user_detail, name='user_detail'),
    path('<int:user_pk>/followers', views.followers, name='followers'),
    path('<int:user_pk>/followings', views.followings, name='followings'),
    path('<int:user_pk>/follow', views.follow, name='follow'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

movie_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

movie_pjt/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name="follower",blank=True)
    
    def __str__(self):
        return self.username

movie_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pass

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email',)

movie_pjt/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email',)

accounts/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST

from .forms import UserCustomCreationForm

# Create your views here.
@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('movies:list')
    else:
        user_form = UserCustomCreationForm()
    context = {'form': user_form}
    return render(request, 'accounts/forms.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:list')
    else:
        login_form = AuthenticationForm()
    context = {'form': login_form}
    return render(request, 'accounts/forms.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:list')
    
@login_required    
def user_list(request):
    User = get_user_model()
    user = User.objects.all()
    return render(request,"accounts/user_list.html",{"Tuser":user})

@login_required
def user_detail(request,user_pk):
    User = get_user_model()
    user = get_object_or_404(User,id=user_pk)
    return render(request,"accounts/user_detail.html",{'Tuser':user})

@login_required
def followings(request,user_pk):
    User = get_user_model()
    user = get_object_or_404(User,id=user_pk)
    return render(request,'accounts/user_followings.html',{'Tuser':user})    
    
@login_required
def followers(request,user_pk):
    User = get_user_model()
    user = get_object_or_404(User,id=user_pk)
    return render(request,'accounts/user_followers.html',{'Tuser':user})    

@login_required
def follow(request,user_pk):
    User = get_user_model()
    me = request.user
    you = get_object_or_404(User,id=user_pk)
    if me != you:
        if you in me.followings.all():
            me.followings.remove(you)
        else:
            me.followings.add(you)
    return redirect('accounts:user_detail',user_pk)
    

movie_pjt/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST

from .forms import UserCustomCreationForm

# Create your views here.
@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('movies:list')
    else:
        user_form = UserCustomCreationForm()
    context = {'form': user_form}
    return render(request, 'accounts/forms.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:list')
    else:
        login_form = AuthenticationForm()
    context = {'form': login_form}
    return render(request, 'accounts/forms.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:list')

accounts/templates/accounts/forms.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="container">
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-info" type="submit" value="확인">
</form>
</div>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}
{% block body %}


<h1>{{Tuser}}</h1>
<h6>
팔로잉 : <a href="{% url 'accounts:followings' Tuser.id %}">{{Tuser.followings.count}}</a>
팔로워 : <a href="{% url 'accounts:followers' Tuser.id %}">{{Tuser.follower.count}}</a>
</h6>

{% if user != Tuser %}
   {{user.user_follow.all}}
   {% if user in Tuser.user_follow.all %}
    <a href="{% url 'accounts:follow' Tuser.id %}">팔로잉</a>
   {% else %}
    <a href="{% url 'accounts:follow' Tuser.id %}">팔로우</a>
   {% endif %}
 {% else %}
   <a href="">Edit profile</a>
 {% endif %}

<hr style="width: 100%; color: #EEEEEE; height: 1px; background-color: #EEEEEE;" />

<h4>
 유저 평가 정보
</h4>
 <!--해당 유저가 작성한 평점 정보가 모두 출력된다.-->
 <ul>
 {% for sc in Tuser.score_user.all %}
  <li>
   <div>
    <h5>
    Title : {{sc.movie.title}}
    <div class="btn btn-success">{{sc.value}}점</div>    
    </h5>
    - {{sc.content}}
   </div>
  </li>
 {% endfor %}
 </ul>
 
 
{% endblock %}

accounts/templates/accounts/user_followers.html
{% extends 'base.html' %}
{% block body %}
팔로워
<ul>
{% for u in Tuser.follower.all %}
    <li>
        {{u}}
    </li>
{% endfor %}
</ul>
{% endblock %}

accounts/templates/accounts/user_followings.html
{% extends 'base.html' %}
{% block body %}
팔로잉
<ul>
{% for u in Tuser.followings.all %}
    <li>
        {{u}}
    </li>
{% endfor %}
</ul>
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends 'base.html' %}
{% block body %}
    {% for u in Tuser %}
        <a href="{% url 'accounts:user_detail' u.id %}">
            <h1>
            {{u}}
            </h1>
        </a>
    {% endfor %}
{% endblock %}